### ISSUE TITLE
PWM example makes no sense

### ISSUE THREAD

**Issue by YemSalat** [nebrius/raspi-llio#1]
Aren't you basically manually turning the pins on and off:

```
var raspi = require('raspi-llio');

var pwm = new raspi.PWM();
raspi.PWM.setMode(0);
raspi.PWM.setClockDivisor(400); // <- YOU ARE IGNORING THIS
raspi.PWM.setRange(1000);

var value = 40;
setInterval(function() { // <- AND JUST SET THE INTERVAL
  if (value == 40) {
    value = 90;
  } else {
    value = 40;
  }
  pwm.write(value);
}, 2000);
```

So you are basically doing manually (in JS) what should be done by hardware.

**Comment by nebrius** [comment]
That's not what that code does at all. Take a look at the amount of time passed to setInterval 😉

**Comment by YemSalat** [comment]
Yep, sorry my bad, thanks for the clarification. I should get more sleep :)
